### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by jatinkumarg** [UriahShaulMandel/BaldPhone#13]
Hey, I am trying to set up this project but I got an error given below:
```
Android resource linking failed
C:\osd\BaldPhone\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:218: error: resource string/authorities (aka com.bald.uriah.baldphone:string/authorities) not found.
error: failed processing manifest.
```
Does anyone know how to fix this?

**Comment by UriahShaulMandel** [comment]
Hi there, I'm the creator of this platform.
You must have already seen it, but I'm adding a similar StackOverflow question here:
https://stackoverflow.com/questions/52035063/android-resource-linking-failed

I'll check on my end and notify you, but I thinks it's probably on your end because it works fine for me.

:)

**Comment by UriahShaulMandel** [comment]
I found out the problem, it's on my end. It will be fixed within a day or two and I'll notify you here.

**Comment by UriahShaulMandel** [comment]
It's fixed, notify me if there are any further issues.
Thank you for being interested in BaldPhone! :)

**Comment by UriahShaulMandel** [comment]
Is it working for you?

**Comment by jatinkumarg** [comment]
@UriahShaulMandel Yea, it's working. Thanks!
