### ISSUE TITLE
BaldPhone is not updating on fdroid

### ISSUE THREAD

**Issue by UriahShaulMandel** [UriahShaulMandel/BaldPhone#251]
Baldphone is not being updated in fdroid, 
@izzysoft or anyone else, do you happen to know why?
Thanks!

**Comment by IzzySoft** [comment]
Let me check (in [my snippet here](https://gitlab.com/snippets/1896503) you can find some hints on how to do that yourself):

* checkupdates lists it (and indeed, `com.bald.uriah.baldphone.yml` has CV on 12.1.0 and contains the corresponding build block, so it was detected)
* updates also has it
* buildserver activity says it tried on May 3rd

In the latter we also find what went wrong. A quite common issue: "could not bring up vm 'builder_default'"… I hope our new build servers go live soon. No worries, it will build eventually (we're currently waiting for some other releases, like Conversations, as well – which luckily made it yesterday after having hung in the queue with the same error for some days).

**Comment by UriahShaulMandel** [comment]
Oh thanks! 
Good to know too about the snippet.
Is there anything I can help with to make it faster? Re-upload the version with a different code?
Thanks?

**Comment by IzzySoft** [comment]
> Good to know too about the snippet.

There are some more useful snippets for F-Droid stuff in my collection if you're interested :wink:

> Is there anything I can help with to make it faster? Re-upload the version with a different code?

No, in a case like this nothing. If the builder VM cannot be brought up, only F-Droid stuff could touch that. Though not even those with access to that machine can do much about it; it's simply retried on the next run, and will finally succeed. Only when there are errors with the build itself (i.e. the VM *was* brought up but failed to build due to e.g. some missing dependency, broken code, whatever – or the `versionCode` was not increased) you devs can help (fix the broken code, increase `versionCode`, etc).

**Comment by UriahShaulMandel** [comment]
Hi, looks like this problem still exists. @IzzySoft do you happen to know when will it be solved? Sorry for disturbing, just some users asking when they'll get their update and I'm not sure what to answer...
Thanks ahead :)

**Comment by IzzySoft** [comment]
No. I can only tell you the status (which you can do yourself with the links I gave you) – and that's still the same (and the same error). As your app is still in my repo (with faster updates), you could suggest them picking it from there instead (if they trust you and me enough). Need an uninstall and reinstall for switching then, though.

We're working on new build server<b>s</b> though – so multiple instead of one – but that also requires a different process (parallel instead of sequential), so it won't be ready by tomorrow obviously. I hope it doesn't take that long anymore and will be ready *before* Rosh Hashanah…

**Comment by UriahShaulMandel** [comment]
OK, thanks! :)
will recommend indeed

**Comment by IzzySoft** [comment]
Good to have a fallback :smile:

**Comment by UriahShaulMandel** [comment]
@IzzySoft its working!
thanks!

**Comment by IzzySoft** [comment]
Finally :smile: Great to hear!
