### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by qazip** [UriahShaulMandel/BaldPhone#8]
Have you thought about publishing baldphone to F-Droid?

**Comment by UriahShaulMandel** [comment]
Hi, and thank you for your issue!
I did think about publishing BaldPhone to F-Droid, and I'm checking into it now.
I'll notify you if, and when it'll be published.

As of now, you can download the APK and use BaldPhone's updating system.

**Comment by Primokorn** [comment]
@qazip You may know Izzy's F-Droid repo. Baldphone can be downloaded [from there](https://apt.izzysoft.de/fdroid/index/apk/com.bald.uriah.baldphone).

@UriahShaulMandel Since Baldphone is mainly developed for elderly or handicapped people they don't know what Github or F-Droid are.
May I suggest you to consider publishing Baldphone on Google Play? I set automatic updates on Google Play for the device of my grandmother.
I already know what I'll have questions from her as soon as the first update will reach her phone lol

**Comment by UriahShaulMandel** [comment]
Hi @Primokorn 
BaldPhone was on the google play, for several months.
Then came [this](https://www.androidpolice.com/2019/01/05/googles-new-sms-and-call-permission-policy-is-crippling-apps-used-by-millions/)
BaldPhone should not be affected, especially because it's Open Source and google can see that no information is being taken.
Iv'e sent a lot of emails, even mailed the ceo of Google in israel, tried for 3 weeks (until the deadline) to convince them to give BaldPhone permission to read the call log but got no response (only bot responses) and sadly had to remove the app from the play store. 
I hope that more users will use the BaldPhone, and perhaps the GitHub repo will have more traffic, and mabye someone from Google will see how cool the project is and will help me to reupload it to the play store.

**Comment by UriahShaulMandel** [comment]
And apparently, I can use a different branch on f-droid, like [this](https://github.com/adolfintel/sine-android/compare/fdroid)
So expect BaldPhone on F-Droid soon :)

**Comment by Primokorn** [comment]
@UriahShaulMandel Thanks for the explanation. F-Droid is a decent alternative (that I use for years) but still hard to explain to an elderly person.

**Comment by DJCrashdummy** [comment]
@Primokorn if you can somehow gain root access of the device, i advise to install [F-Droid Privileged Extension](https://f-droid.org/packages/org.fdroid.fdroid.privileged/) additionally, then you can configure f-droid to check for, download and install updates completely unattended.
...so no explanations needed at all. :wink:

**Comment by Primokorn** [comment]
@DJCrashdummy I know but I don't want to root her phone (too much power for an elderly person).

**Comment by DJCrashdummy** [comment]
@Primokorn 
with an ("unrooted") custom ROM (like LineageOS) you don't need to provide root access at all... simply flash [the zip-package](https://f-droid.org/packages/org.fdroid.fdroid.ota/) and you are ready to go. even some custom ROMs have it pre-installed/-flashed by default, but i'm not sure which of them.

or at some custom ROMs you can also deactivate root access or also unroot the phone completely after installing [F-Droid Privileged Extension](https://f-droid.org/packages/org.fdroid.fdroid.privileged/)... no idea if this is possible with a stock android (never even thought about it, nor done it).

--- 

or e.g. i install and activate root on a bunch of phones, but granted root access just for [AdAway](https://f-droid.org/packages/org.adaway/), [oandbackup](https://f-droid.org/packages/dk.jens.backup/) and if needed [Wrong PIN Shutdown](https://f-droid.org/packages/org.nuntius35.wrongpinshutdown/)... a very short timer to ask for root permissions (default answer is "no") does the rest.
i only got a very few questions, "what is this window which disappears by itself?", but never had a problem with a messed up phone by their users via root access. :wink: 

but that's clearly getting OT, sorry for that.

**Comment by UriahShaulMandel** [comment]
Made me think perhaps I can release a fork of LineageOS, preinstalled with BaldPhone, with system access so it has auto-update enabled.

**Comment by DJCrashdummy** [comment]
@UriahShaulMandel not sure if this is worth the effort: because you need an pretty techy "admin" resp. friend to flash no matter what custom ROM. and after that, setting up f-droid to do the auto-update is easy peasy at least for this techy admin... and if the *"F-Droid Privileged Extension"* is preinstalled, not just for them.
so IMHO, publishing via fdroid has a much much higher priority than an own BaldPhone ROM! not to mention that the user base of an fdroid-build would be much higher then the userbase of an own ROM, but with considerable less effort.

**Comment by UriahShaulMandel** [comment]
Yes, right now I'm on vacation, but as soon as I come back, I'll release BaldPhone on F-Droid

**Comment by DJCrashdummy** [comment]
no pressure from my side... i just wanted to help organize priorities and balance effort & use.
enjoy your vacation @UriahShaulMandel! :beach_umbrella:

**Comment by UriahShaulMandel** [comment]
Hi, mainly targeted towards @IzzySoft,

I want to release BaldPhone to F-Droid main repo too as you suggested.

I've added an F-Droid branch, which doesn't use BaldPhone in-app updating mechanism, you can check it out [here](https://github.com/UriahShaulMandel/BaldPhone/tree/fdroid)

I found a way to keep working only in the master branch, and only before releasing a new version I merge the new changes into the F-Droid Branch.

With that said, I've encountered a problem:
The master flavor, used by a lot of users, depends on the releases mechanism of GitHub, 
It uses [Releases API](https://developer.github.com/v3/repos/releases/) to find the last version, and if it's newer than the current one, BaldPhone downloads the APK attached with the version.
I understood that the official repo of F-Droid uses the releases mechanism too, and compiles the last release itself.
So my question is, can F-Droid detect that a new release was released, but compile a different branch, and not the branch that was released?
If it can't, the only workaround I can think of is to publish releases with the F-Droid compatible code, but attach the master APK, which sounds to me like a bad practice, because the attached APK won't match the source code. It'll work, with both of the versions, but I would like to avoid this workaround if possible.

Any suggestions?

**Comment by IzzySoft** [comment]
I'm not a dev and neither a packager, so please forgive any inconsistencies etc.:

Are you familiar with build flavors? That's what's normally used in such cases. AFAIR F-Droid cannot easily work on a different branch – but then, what might work (and here comes the "I'm no packager" part):

* you work on the master branch. You make a "normal" release, and tag it as usual (i.e. creating a tag matching the versionCode)
* now you merge to/update the fdroid branch, and create a new tag on its latest commit, naming it e.g. `fdroid-<versionCode>`. So that tag points into the fdroid branch.
* at F-Droid, we tell the updater to watch out for tags named `fdroid-%c`. So the update checker finds the new F-Droid tag (while it would ignore all the non-fdroid tags), and creates a new build block for it. So the build server would fetch the tree at that commit – and should get the fdroid branch (that's the only one having it).

Not 100% sure if that works that way – because if it is, why was there talk about issues with branches? So build flavors (aka build variants) would be the better approach – and should also save you from maintaining two branches and from the merging otherwise needed.

**Comment by UriahShaulMandel** [comment]
Hi @IzzySoft , I added build variants as you suggested.
You're right, it's much easier and overall a better technique, thanks!

I did it like [this project](https://github.com/fennifith/Alarmio), now I have two build variants,
baldUpdates - the current system of updating via the apk attached in the latest release
and
fDroid - the one which F-Droid will compile and upload to the store

Is there anything else I need to do before uploading BaldPhone to F-Droid? 
Thanks again!

**Comment by IzzySoft** [comment]
The only thing coming to my mind is establishing Fastlane structures (see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) to get an idea: no need to *install* Fastlane, just create the structures and fill in screenshots etc). That way you could provide screenshots, and also could maintain summary/description yourself – even for multiple locales (I guess you'd like to have at least Ivrit next to English), plus per-release changelogs (which then would be shown "inline" with the app description when viewing it in the client). Then have a tag covering this – and I'd say after that go for it. If we missed anything, we'll find out then.

When ready for the RFP, just let me know: I can provide the metadata template as that's mostly a copy-paste from my repo, just with the build details needing to be added.

**Comment by UriahShaulMandel** [comment]
Hi, I added the screenshots and the texts in [this](https://github.com/UriahShaulMandel/BaldPhone/commit/952b8dc92fd9d6aff679d5a5edb6735ecec73557) commit.
Right now I'll keep things English only, there are some things I have to do first.
But in some weeks from now, I'll update the texts and screenshots, and translate them to multiple languages. I would still like to have BaldPhone in the store right now as is.

The only thing I wasn't sure about was how to add the changelog, which I didn't add. Can F-Droid just use the changelog from the releases? Aside from that, I think BaldPhone is ready :)

**Comment by IzzySoft** [comment]
There are two ways to provide access to changelogs: via a link ( `Changelog:`) in Metadata (which the user then has to "press" explicitly), or via `fastlane/metadata/android/en-US/<versionCode>.txt` changelog files in Fastlane (which get shown "inline"). One doesn't exclude the other, so you can have both.

Fastlane structure looks good! Though I'd recommend not to use "framed" screenshots: the frames waste useful screen estate. Consider your "bald ones" evaluating your app on a 5" mobile screen: the less "clutter" around, the better they can visualize the "real important stuff". Just a recommendation, not mandatory – but especially in context of this app's purpose I felt the need to mention it :wink:

I'd setup the RFP in the evening if you wish – to give you a little time to (optionally replace the screenshots by non-framed ones and) tag the latest commit (F-Droid grabs only what is tagged, so currently it would not "see" the Fastlane structures).

**Comment by UriahShaulMandel** [comment]
I've done it, I think I'll show the changelog via a link at the meantime.
Thank you very much for everything!

**Comment by IzzySoft** [comment]
Thanks, Uriah – and [here you go](https://gitlab.com/fdroid/rfp/issues/1050). If you tell me where the changelog can be found, I'll add that link as well. Either you hid it too well, or Github's UI is not that "big, simple and friendly" as Baldphone's UI. Or the changelog is really missing…

**Comment by IzzySoft** [comment]
Yay, the bot gave a thumbs up! Marked it for our packagers to review and "bundle". One thing the bot complains about concerns your own builds: please take a look at its report and adjust your gradle for increased security :wink:

**Comment by UriahShaulMandel** [comment]
@IzzySoft Thank you very much :)


> If you tell me where the changelog can be found

I thought maybe to use [this](https://github.com/UriahShaulMandel/BaldPhone/releases) as a changelog, saw another app on F-Droid which did it

> please take a look at its report and adjust your gradle for increased security

Ok, TBH I'm not sure what does it mean but I'll do some research

**Comment by IzzySoft** [comment]
The other apps have a changelog there (i.e. they add release notes listing what has changed). Ah, wait… those are no headers :rofl: Sorry, Uriah, but the formatting is a bit confusing. Instead of starting each item with a hash (`#`), please use an asterisk (`*`). It's Markdown that gets rendered. To give you visuals:

```
# This will be a header
# and this, too
* this is a bullet point
* and this another one
```

Renders to:

> # This will be a header
> # and this, too
> * this is a bullet point
> * and this another one

Looks familiar? May I suggest you switch that to `*` listings, and then we add that as Changelog link?

**Comment by UriahShaulMandel** [comment]
> Sorry, Uriah, but the formatting is a bit confusing

You're right, looking at this now and I'm quite embarrassed I wrote it like this from the beggining😅
From now on I'll use asterisks, Thanks!


BTW, do you know how much time will take for the packagers to review and "bundle" BaldPhone? nothing urgent, just interested.

**Comment by IzzySoft** [comment]
Added the URL to metadata (and you know you can always edit release notes afterwards? You might wish to do that for the newest 2..3).

As for timing: that very much depends on when someone finds time. Can be quite immediate, or take a few weeks. We're always understaffed, unfortunately. If you want to speed up things, the way would be running a copy of fdroidserver yourself to test the "build recipe" (aka "builds with fdroidserver"), and then open the merge request yourself. But that's a bit of work for the first one, so noone expects you to (though of course you're welcome :wink:).

**Comment by IzzySoft** [comment]
OK, got merged today – so it should show up within about a week at max. One issue we both missed: the summary is too long.

![Screenshot](https://gitlab.com/fdroid/rfp/uploads/ecf0eff5207a653ffd2a1949b3e57f61/image.png)

It's currently 89 chars. Max permitted is 80. Suggestion: strike the first 3 words? "replaces the phone's interface with a bigger, simpler and friendlier one" looks fine to me. If you could adjust that before tagging the next version it would be great. (PS: also note the one word I changed. You "replace with"/"replace by" or "change into" – but you don't "replace into" or "change with" – at least not in this context; you of course can "change with Joël" or something like that :laughing:)

**Comment by UriahShaulMandel** [comment]
> OK, got merged today – so it should show up within about a week at max

Great :)  Thank you very much!

>Max permitted is 80.

I changed the description, please take a look at [this](https://github.com/UriahShaulMandel/BaldPhone/commit/0ea4c39d261687b4ff296bd00d9ea910ae994100).

**Comment by DJCrashdummy** [comment]
i don't want to sound nitpicking (especially because english isn't my mother tongue either), but...

> Change your phone's interface with a big, simple and friendly one

should rather be *"Change your phone's interface **into** a big, simple and friendly one"*
...you can *"replace something **with** ..."* and *"change something **into** ..."*.

---

But IMHO **replacing** is in this case more accurate than **changing**! because you are changing nothing, rather adding/installing a launcher and (hopefully) replacing the used launcher. :wink: 

so if you ask me, i would go with:
*Replace your/the phone's interface with a big, simple and friendly one*

**Comment by IzzySoft** [comment]
Yes, as the DJ sang (and note that's what my previous comment also said: "change into" or "replace with"). And I also agree that you are rather "replacing" here, @UriahShaulMandel :wink:

And well, is it nitpicking when 3 non-natives argue about the correct phrasing? Or is that rather "foreign politics"? :laughing:

**Comment by UriahShaulMandel** [comment]
You're both right, I changed, waiting for tests to complete and releasing :)
https://github.com/UriahShaulMandel/BaldPhone/blob/ca4dcf531e5308af64056dc4bdce192d25a90381/fastlane/metadata/android/en-US/short_description.txt#L1

**Comment by IzzySoft** [comment]
Great! Will be automatically picked up (if I remember correctly, we've set it up that way, to check the tags).

**Comment by UriahShaulMandel** [comment]
Hi, I saw BaldPhone in F-Droid, very cool :)
But I noticed a few problems:
1. The latest release is shown as `Version 11.3.4 (80)`, but I published a new one.
2. "App not installed" error is shown when trying to install the apk

**Comment by IzzySoft** [comment]
1. As this was the initial merge, our system could not have known about "updates" (of what was not yet there). The new version should appear soon (we did enable auto update check, didn't we?)
2. Could it be you have some "remains" from a previous install there? Keep in mind the signature has changed, so the two would certainly clash. Can you retry with a "clean device"?
3. Would you prefer I keep your app a little longer in my repo? You tell me when I shall remove it (to avoid users getting confused when installing from one source and trying to update from another – again, signature mismatch).

**Comment by DJCrashdummy** [comment]
ad 1. auto update [seems to be enabled](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.bald.uriah.baldphone.yml#L31) and that it [has worked for `Version 11.3.4 (80)`](https://f-droid.org/packages/com.bald.uriah.baldphone/). :+1: :clap:

**Comment by UriahShaulMandel** [comment]
Everything is working! @DJCrashdummy and @IzzySoft Thank you very very much!
@qazip I thought you may want to know too.
The only thing I noticed, which isn't that important, is that BaldPhone is not in the "latest" tab in the F-Droid app. Thought it could be nice to have there, so more users will see it.

> Would you prefer I keep your app a little longer in my repo? You tell me when I shall remove it (to avoid users getting confused when installing from one source and trying to update from another – again, signature mismatch).

@IzzySoft You know better than me, but I don't see any problem with keeping BaldPhone in your repo too. The more the better :)
Thank you all, I'm closing this issue.

(You can still comment in this issue if you have something to add)

**Comment by IzzySoft** [comment]
> that BaldPhone is not in the "latest" tab in the F-Droid app.

That tab is mislabeled for a while now and should read "featured". In order to have an app show up there, it must have screenshots *and* per-release changelogs. Baldphone's Fastlane directory lacks the latter.

As for the "double keep": Updates are definitely faster with my repo, as long as you keep attaching the APKs. Users who installed it from one repo won't get update recommendations from the other. The only thing I'm not sure about is: even with both repos having the same version, which one would be recommended to the user on first install? I've just checked: though the one from the main repo is listed one day newer, it's the APK from my repo (I had expected the official one getting preference). Seems like the algorithm is "pick the (first) one with the highest `versionCode`". I'd rather give the "more trusted source" (i.e. the official repo) preference – but that's nothing we can change. We could only work around that (e.g. using a different package name) – but is it worth the effort?

Just remember that cross-updates are not possible; so whatever source a user is installing it from initially, (s)he is stuck with until uninstall. Which is why I usually remove apps from my repo at this point, with few exceptions. Some apps have their APKs in both places:

* beta/test versions in mine (usually going by different package names, like appending `.beta`: Bitmask, RiseUp)
* different feature sets (things not complying with F-Droid's inclusion policy but meeting mine: MTG Familiar)
* two apps I've initially installed from my repo and was too lazy to switch (that I should fix soon: one (aRevelation) doesn't have its own data, so switching should be easy – and the other (Camera Roll) currently has its development stalled anyway)
* one returned to my repo when F-Droid didn't deliver an important update in time (due to technical issues) and I could remove again
* one (FairEmail) was brought back to my repo on demand of several users, as the app updates almost daily and F-Droid thus skips a few versions everytime
* several cannot be updated in F-Droid anymore due to introducing dependencies not conforming to F-Droid's inclusion criteria (e.g. FBReader)

Shall we have a poll? 😄 With the two of us undecided, what do the other two you just pinged think?

**Comment by UriahShaulMandel** [comment]
@IzzySoft After doing a lot of thinking I think it's best to remove the current version of BaldPhone from your repo, and to add a beta version of BaldPhone there instead. I really need to start ab testing and it can solve both of the problems at once. Is it OK? How should I do it? Can you take pre-released versions and change their package name?

Again, Thank you very much for everything!

**Comment by IzzySoft** [comment]
That would be perfect, and I gladly comply!

I can't change package names (and neither can I sign), so I'd need signed APKs with a different package name to start with. You could use a [build variant](https://developer.android.com/studio/build/build-variants) for that, which basically is identical to the "standard one" with the exception of using a different package name (I'd suggest appending `.beta` to the real one, so `com.bald.uriah.baldphone.beta` – Gradle has an automatism for that even, `applicationIdSuffix` (see the example on the linked page), so you'd just need to provide the suffix and it would join the two on build; F-Droid's build server doesn't support that currently, so only use it for the beta build, please). A "product flavor" (described on the same page) would work as well, whichever is easier for you.

Then we need to take care with the tags/releases, to have the F-Droid build process ignore the betas (and mine ignore the "real releases"). Update check at F-Droid must use `%c` currently (tag name corresponds to versionCode) – so for the betas, you could use `%v` instead (tag name corresponds to versionName). Easy to adjust on my end (just let me know when it's ready), and no adjustments needed for the official repo. Note that for version compare, my update checker will ignore letters (so e.g. `1.0.2-alpha3` would be considered newer than `1.0.2-beta1` because `1.0.2-3 > 1.0.2-1` – you have no idea what funny tag names people come up with making that necessary).

**Comment by DJCrashdummy** [comment]
> [...] BaldPhone is not in the "latest" tab in the F-Droid app. Thought it could be nice to have there, so more users will see it.

just an idea: maybe it is possible to introduce BaldPhone at [#TWIF](https://f-droid.org/en/2018/04/27/this-week-in-fdroid.html)? ...because i really don't know a similar FOSS project and think thereby it will get some additional attention (which it definitively deserves).

citing from the last TWIF:
> Do you have important app updates we should write about? Send in your tips via [Mastodon](https://joinmastodon.org/)! Send them to [@fdroidorg@mastodon.technology](https://mastodon.technology/@fdroidorg) and remember to tag with [#TWIF](https://mastodon.technology/tags/twif). Or use the [TWIF submission thread](https://forum.f-droid.org/t/twif-submission-thread) on the forum. The deadline to the next TWIF is Thursday 12:00 UTC.
>
> General feedback can also be sent via Mastodon, or, if you’d like to have a live chat, you can find us in #fdroid on [Freenode](https://freenode.net/), on Matrix via [#fdroid:f-droid.org](https://matrix.to/#/#fdroid:f-droid.org) or on [Telegram](https://t.me/joinchat/AlRQekvjWDTuQrCgMYSNVA). All of these spaces are bridged together, so the choice is yours. You can also join us on the [forum](https://forum.f-droid.org/).

---

sorry for adding this to this old issue, but i just wanted to mention it and not sure if it deserves its own issue.

**Comment by UriahShaulMandel** [comment]
Thank you very much @DJCrashdummy !
It looks great, I'll send BaldPhone now :)

**Comment by UriahShaulMandel** [comment]
@DJCrashdummy do you know how to submit BaldPhone to TWIF? I went to the forums and it's not clear...

**Comment by DJCrashdummy** [comment]
well, not really... i'm just a FOSS-enthusiast and advanced user (resp. reader in this case) who really cares.

i guess regarding TWIF it is the best to contact the fdroid-team via [Mastodon](https://mastodon.technology/@fdroidorg) with [#TWIF](https://mastodon.technology/tags/twif) or [their forum](https://forum.f-droid.org/t/twif-submission-thread) and ask/suggest to include BaldPhone.
additional i'm quite sure it is more likely to get picked up resp. get picked up faster, if there is already a nice sober text/article they can use.

...if you face problems, i guess they would be also glad to help at Freenode, Matrix, Mastodon, Forum or Telegram (as also linked in the previous quote).
...or perhaps @IzzySoft can help in this case too?

**Comment by IzzySoft** [comment]
I'm not involved with TWIF. But sending a note to `@fdroid@mastodon.technology` on Mastodon should raise the attention. Their forum thread which you linked probably as well. Not sure if there's a separate (GitLab) repo used for tracking (none going by a name including "twif").

**Comment by UriahShaulMandel** [comment]
Hi @IzzySoft ,
I've released an update a few days ago, and it doesn't show up on the official F-Droid repo. How long should it take? Perhaps the build failed? How can I know?

**Comment by IzzySoft** [comment]
Oh, it sometimes. Cannot show up before a new index is released (which is easiest to check via my repo browser [here](https://apt.izzysoft.de/fdroid/index.php?repo=main) – which currently tells you the last index update happened on August 13). You can also check build activities [here](https://f-droid.org/wiki/index.php?title=Special%3ARecentChanges&limit=250&hidebots=0) and see there haven't been any since your release.

(Apologies for the delayed response, but I was AFK)

**Comment by UriahShaulMandel** [comment]
Ok, thanks!
Does updating always take that long?

**Comment by IzzySoft** [comment]
No. Sometimes it takes longer. And other times it just happens the next day. Unpredictable due to the manual steps involved which only a single person can perform (the one who has the keys to sign with).

**Comment by UriahShaulMandel** [comment]
Not sure why it's still open, everything is working :)
Thank everyone who helped, I'm closing this issue

**Comment by IzzySoft** [comment]
@UriahShaulMandel maybe you kept it open because we wanted to switch your copy in my repo to test builds, while keeping production builds in the official repo? Currently both have the production builds.

Oh, and you might like to add the attachment to your project (after unpacking) – just made for you :wink:

[baldphone-fastlane.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3745305/baldphone-fastlane.zip)
